In [ ]:
!pip install numpy


In [2]:
import numpy as np

In [9]:
# vector
# [1, 2, 3]
a = np.array([1,2,3])
print(a.shape)
a[0] = 5
print(a[0])

# matrix
# [[1,2,3], [3,4,5]]
b = np.array([[1,2,3], [4,5,6]])
print(b.shape)

# tensor
c = np.array([[[1,2,3], [4,5,6]],
            [[1,2,3], [4,5,6]],
            [[1,2,3], [4,5,6]],
            [[1,2,3], [4,5,6]]])
print(c.shape)

(3,)
5
(2, 3)
(4, 2, 3)


In [16]:
print(np.full((2,2), 7))
print(np.ones((2,2)))
print(np.zeros((3,3)))
print(np.eye(7))

[[7 7]
 [7 7]]
[[1. 1.]
 [1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


In [18]:
np.random.random((2,3)) * 10

array([[7.74239726, 2.72616899, 3.27334805],
       [1.57858926, 4.47721013, 6.91431573]])

ARRAY INDEXING

In [25]:
a = np.arange(1,13).reshape(3,4)


In [26]:
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [27]:
b = a[:, 2:]
print(b)

[[ 3  4]
 [ 7  8]
 [11 12]]


In [28]:
b = a[:, :2]
print(b)

[[ 1  2]
 [ 5  6]
 [ 9 10]]


In [31]:
b = np.copy(a[:-2, :1])
print(b)

[[10]]


In [32]:
b[0,0] = 10
print(a)

[[10  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [33]:
a = np.arange(1,13).reshape(3,4)

In [34]:
b = a[1, :]
print(b)

[5 6 7 8]


In [35]:
b = a[:, 1]
print(b)

[ 2  6 10]


In [38]:
a[[0,1,2],[0,1,0]]

array([1, 6, 9])

In [39]:
a[np.arange(3),np.arange(3)]

array([ 1,  6, 11])

In [40]:
a = np.arange(1,13).reshape(3,4)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [44]:
# mask
bool_idx = a > 2

In [45]:
a[bool_idx]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [46]:
print(a[a>2])

[ 3  4  5  6  7  8  9 10 11 12]


In [47]:
a.dtype

dtype('int64')

In [49]:
# element wise

x = np.array([
    [1,2],
    [3,4]]
)
y = np.array([
    [5,6],
    [7,8]]
)


In [50]:
x + y


array([[ 6,  8],
       [10, 12]])

In [51]:
x * y

array([[ 5, 12],
       [21, 32]])

In [52]:
# dot product
x.dot(y)

array([[19, 22],
       [43, 50]])

In [53]:
np.dot(x,y)

array([[19, 22],
       [43, 50]])

In [54]:
# Sum, mean, max, min
a = np.arange(1,13).reshape(3,4)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [55]:
np.sum(a)

78

In [56]:
np.max(a, axis = 0)

array([ 9, 10, 11, 12])

In [57]:
a.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [58]:
a = np.arange(1,13).reshape(3,4)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [60]:
np.tile(a, (2, 2))

array([[ 1,  2,  3,  4,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  5,  6,  7,  8],
       [ 9, 10, 11, 12,  9, 10, 11, 12],
       [ 1,  2,  3,  4,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  5,  6,  7,  8],
       [ 9, 10, 11, 12,  9, 10, 11, 12]])

In [62]:
b = np.array([1,1,1,1])

In [63]:
#broadcasting
a+b

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])